server:
  port: 4343
  servlet:
     context-path: /Boot-ems

spring:
  datasource:
     driver-class-name: oracle.jdbc.driver.OracleDriver
     url: jdbc:oracle:thin:@localhost:1521:xe
     username: system
     password: tiger
  jpa:
    show-sql: true
    hibernate:
       ddl-auto: update
  mvc:
     view:
        prefix: /
        suffix: .jsp
  
